### ISSUE TITLE
Wrong namespaces are generated if project doesn't use the default Laravel structure.

### ISSUE THREAD

**Issue by mabdullahsari** [spatie/laravel-morph-map-generator#1]
First of all, thanks for Laravel Beyond CRUD!

The package seems to be generating wrong namespaces for an application structure like this:

```
src
   - App
   - Domain
      - Shared
         - Models
            - Country.php
   - Support
```

The derived class name for `Country` becomes `Src/Domain/Shared/Models/Country` whereas it should not be prefixed with `Src/`. I believe this is due to the default value of `basePath` in `DiscoverModels`. I suppose making this value configurable would fix this issue. I'm glad to submit a PR if you are willing to merge it.

**Comment by freekmurze** [comment]
Yup, send a PR 👍 Make sure to include tests!

Thanks for the kind words on our work!
